#!/bin/bash
# Script getting db from remote environment and get it uploaded to local drupal.

# Trapping CTRL-C
trap ctrl_c INT
trap ctrl_c SIGINT
trap ctrl_c SIGTERM

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

# Helper functions for console output
echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }


echo-green 'Checking settings for getting db dump...';
if [ "$SSH_CRED" = "" ]; then
    echo-red 'Can not get connection to remote environment';
    echo-red '$SSH_CRED variable is empty or not defined. Define it in docksal-local.env file. https://docs.docksal.io/stack/configuration-variables/#docksal-environment';
    exit;
fi

if [ "$REMOTE_DB_NAME" = "" ] ; then
    echo-red 'Can not get db dump';
    echo-red '$REMOTE_DB_NAME variable is empty or not defined. Define it in docksal-local.env file. https://docs.docksal.io/stack/configuration-variables/#docksal-environment';
    exit;
fi

DUMP_FILES=$(ssh $SSH_CRED "ls /var/lib/mysql_backup/$REMOTE_DB_NAME.sql.gz")
if [ "$DUMP_FILES" = "" ] ; then
    echo-red 'Can not find any dump for db $REMOTE_DB_NAME or ssh credentials are wrong';
    exit;
fi

DRUSH="drush --root=/var/www/${DOCROOT}"
echo-green 'Looks ok. downloading db dump...';
scp $SSH_CRED:/var/lib/mysql_backup/$REMOTE_DB_NAME* ./

echo-green 'Dropping local db and loading db dump...';
fin exec "${DRUSH} sql-drop -y"
fin exec "zcat < ${REMOTE_DB_NAME}.sql.gz | ${DRUSH} sqlc"
if [ -f "${REMOTE_DB_NAME}-cache-structure.sql.gz" ]; then
  fin exec "zcat < ${REMOTE_DB_NAME}-cache-structure.sql.gz | ${DRUSH} sqlc"
fi

echo-green 'Adjusting drupal settings...';

echo-green 'Setting admin password to "admin"';
fin exec "${DRUSH} upwd admin admin"
fin exec "${DRUSH} cr"
rm -rf ./${REMOTE_DB_NAME}*
